language: php

php:
  - '7.4'
  - '8.0'

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

install: composer install --no-interaction --prefer-dist --no-suggest --no-progress --optimize-autoloader

before_script: composer update --no-interaction --no-suggest --no-progress $PREFER_LOWEST

script: vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: always
